### ISSUE TITLE
needs a flake.nix

### ISSUE THREAD

**Issue by nixinator** [IHaskell/learn-you-a-haskell-notebook#16]
I think Jupiter can be built from source with nix . so nixifying this project might be possible.

I'll put it on my TODO list.

**Comment by nixinator** [comment]
well well well, looks like @DavHau has already worked on this and has made a PR!

**Comment by DavHau** [comment]
Meeting robots from the future in the train to haskell. What a journey!

**Comment by DavHau** [comment]
The flake doesn't support `x86_128-linux` yet. I hope you are downward compatible.

**Comment by nixinator** [comment]
I'll be consumed by the the dockerapocalypse before then...

**Comment by jamesdbrock** [comment]
There is now a `flake.nix` from #15 

But nixifying this whole project would be great. 

Possible starting points: 

* https://github.com/IHaskell/IHaskell/blob/master/flake.nix
* https://github.com/tweag/jupyterWith/blob/main/flake.nix

**Comment by jamesdbrock** [comment]
The `flake.nix` actually is a nixification of this whole project. And I just updated it to the latest jupyterWith. Thx again @DavHau .
